baseURL = "http://foniod.org/"
languageCode = "en-us"
title = "Foniod"
enableGitInfo = true
theme = "book2"
publishDir = "../docs"

[params]
MainMenuBundle = "/main-menu"
BookMenuBundle = "/docs/menu"
BookLogo = "svg/logo.svg"
