var N = null;var sourcesIndex = {};
sourcesIndex["bpf_sys"] = {"name":"","files":["headers.rs","lib.rs","perf_reader.rs","uname.rs"]};
sourcesIndex["cargo_bpf"] = {"name":"","files":["main.rs"]};
sourcesIndex["cargo_bpf_lib"] = {"name":"","files":["accessors.rs","bindgen.rs","build.rs","build_constants.rs","lib.rs","llvm.rs","load.rs","new.rs","new_program.rs"]};
sourcesIndex["example_probes"] = {"name":"","dirs":[{"name":"mallocstacks","files":["mod.rs"]},{"name":"vfsreadlat","files":["mod.rs"]}],"files":["lib.rs"]};
sourcesIndex["probes"] = {"name":"","dirs":[{"name":"iotop","files":["mod.rs"]},{"name":"knock","files":["mod.rs"]}],"files":["lib.rs"]};
sourcesIndex["redbpf"] = {"name":"","dirs":[{"name":"load","files":["loader.rs","map_io.rs","mod.rs"]},{"name":"sys","files":["mod.rs","perf.rs"]}],"files":["cpus.rs","error.rs","lib.rs","perf.rs","symbols.rs","xdp.rs"]};
sourcesIndex["redbpf_iotop"] = {"name":"","files":["redbpf-iotop.rs"]};
sourcesIndex["redbpf_macros"] = {"name":"","files":["lib.rs"]};
sourcesIndex["redbpf_probes"] = {"name":"","dirs":[{"name":"kprobe","files":["mod.rs","prelude.rs"]},{"name":"socket_filter","files":["mod.rs","prelude.rs"]},{"name":"tc","files":["mod.rs"]},{"name":"uprobe","files":["mod.rs","prelude.rs"]},{"name":"xdp","files":["mod.rs","prelude.rs"]}],"files":["bindings.rs","helpers.rs","lib.rs","maps.rs","net.rs","registers.rs","socket.rs"]};
sourcesIndex["redbpf_tcp_knock"] = {"name":"","files":["redbpf-tcp-knock.rs"]};
createSourceSidebar();
